export const regions = [
  { id: 1, data: '서울' },
  { id: 2, data: '경기' },
  { id: 3, data: '인천' },
  { id: 4, data: '부산' },
  { id: 5, data: '대전' },
  { id: 6, data: '대구' },
  { id: 7, data: '울산' },
  { id: 8, data: '세종' },
  { id: 9, data: '광주' },
  { id: 10, data: '강원' },
  { id: 11, data: '충북' },
  { id: 12, data: '충남' },
  { id: 13, data: '경북' },
  { id: 14, data: '경남' },
  { id: 15, data: '전북' },
  { id: 16, data: '전남' },
  { id: 17, data: '제주' },
];

export const categories = [
  { id: 1, data: '골프' },
  { id: 2, data: '농구' },
  { id: 3, data: '댄스' },
  { id: 4, data: '무도' },
  { id: 5, data: '배드민턴' },
  { id: 6, data: '배구' },
  { id: 7, data: '복싱' },
  { id: 8, data: '수영' },
  { id: 9, data: '야구' },
  { id: 10, data: '요가' },
  { id: 11, data: '유도' },
  { id: 12, data: '축구' },
  { id: 13, data: '탁구' },
  { id: 14, data: '테니스' },
  { id: 15, data: '풋살' },
  { id: 16, data: '필라테스' },
  { id: 17, data: '헬스' },
  { id: 18, data: '기타' },
];

export const etcs = [
  { id: 1, data: '골대' },
  { id: 2, data: '냉난방' },
  { id: 3, data: '대기실' },
  { id: 4, data: '대형차량' },
  { id: 5, data: '로비' },
  { id: 6, data: '마이크' },
  { id: 7, data: '바닥' },
  { id: 8, data: '와이파이' },
  { id: 9, data: '일반차량' },
  { id: 10, data: '정수기' },
  { id: 11, data: '조명' },
  { id: 12, data: '창문' },
  { id: 13, data: '샤워실' },
  { id: 14, data: '탈의실' },
  { id: 15, data: '화장실(실내)' },
];
